---
repos:
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.20.3
    hooks:
      - id: ansible-lint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
